spring.r2dbc.url=r2dbc:mariadb://localhost:3306/aiagent
spring.r2dbc.username=root
spring.r2dbc.password=049206
spring.sql.init.mode=always

jwt.secret=your-super-secret-key-at-least-32-chars!!
jwt.expiration=86400000

# OpenAI
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini

# Groq
spring.ai.openai.groq.api-key=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
spring.ai.openai.groq.base-url=https://api.groq.com/openai
spring.ai.openai.groq.chat.options.model=llama-3.3-70b-versatile